### ISSUE TITLE
Static Analysis#5 - Empty catch block

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#10]
**Resolution Method - 빈 catch 블록 채우기**

- [x] Mode/Buzzer.java - line 51
<img width="297" alt="Screen Shot 2020-06-17 at 6 56 17 PM" src="https://user-images.githubusercontent.com/24283401/84884064-3a878b80-b0cc-11ea-944f-5cef04a22688.png">

**Comment by dasd412** [comment]
System.err.print()문을 안에 채웠습니다.
