### ISSUE TITLE
Static Analysis#6 - Assignment of parameter 'X' is not allowed

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#11]
Resolution Method - parameter를 넘겨줄 때, 미리 할당해서 넘겨주기

- [x] Mode/Stopwatch.java - line 132
<img width="419" alt="Screen Shot 2020-06-17 at 7 02 36 PM" src="https://user-images.githubusercontent.com/24283401/84884770-1d06f180-b0cd-11ea-9cbc-cce50dad35fb.png">

- [x] Mode/Stopwatch.java - line 137
<img width="319" alt="Screen Shot 2020-06-17 at 7 02 55 PM" src="https://user-images.githubusercontent.com/24283401/84884813-27c18680-b0cd-11ea-8939-7935c40c66ec.png">

**Comment by dasd412** [comment]
1.calculateTime()호출 하기 전 미리 calendar.getInstance() 호출하는 걸로 수정
2.return time에서 return (hour*3600+min*60+sec);으로 수정하고 time 삭제
