### ISSUE TITLE
Static Anaylsis#7 - Variable 'X' must be private and have accessor methods

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#12]
Resolution Method - 변수를 private 으로 변경하고 getter/setter 추가

- [x] Mode/TimeKeep.java
<img width="437" alt="Screen Shot 2020-06-17 at 7 07 18 PM" src="https://user-images.githubusercontent.com/24283401/84885277-c4842400-b0cd-11ea-8c3a-4091fd342d6b.png">

**Comment by dasd412** [comment]
접근자 추가 완료,
