### ISSUE TITLE
System Testing#3 - Set Alarm

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#13]
알람 재설정 시에 시간이 초기화 된다.
-> 알람 재설정 시에 기존의 알람 시간을 불러오도록 수정

**Comment by 1hk-star** [comment]
"알람 재설정 시에 시간이 초기화 된다.
-> 알람 재설정 시에 기존의 알람 시간을 불러오도록 수정" 이부분의 경우 저희가 알람 설정이 기존 알람을 수정하는 방식이 아니라
0개의 알람에서 계속 알람을 만들면서 최대 4개까지 쌓아가는 방식으로 구현을 하고 있어서 setalarm을 누르면 초기값으로 0 0 0을 표현하고 있습니다.
그래서 위의 경우에는 버그가 아닌것같습니다.
