### ISSUE TITLE
System Testing#4 - Set Alarm

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#14]
설정이 끝난 후의 알람의 인덱스가 변경됨
-> 설정이 끝난 후의 알람의 인덱스가 그대로 유지되도록 변경

**Comment by 1hk-star** [comment]
[bug 수정 v1에 반영]
설정이 끝난 직후 해당 알람 설정 시간이 알람모드의 가장 처음 노출되도록 변경.
알람에서 현 노출 시간이 a이면 change mode를 통해 다른모드를 거쳐 다시 알람으로 와도 a가 가장 먼저 노출.
알람을 4개이상 설정을 하게 되면 알람 리스트에 있는 알람중 가장 먼저 설정했던 알람이 삭제됨.
