### ISSUE TITLE
System Testing#5 - Check Beep

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#15]
알람 여러개 설정 후 알람모드에서 버튼을 눌렀을 때 버저가 멈추지 않음
-> 여러 개의 알람이 동시에 울릴 때 버튼을 누르면 beep이 꺼지도록 수정

**Comment by 1hk-star** [comment]
동시 알람이 울려도 버튼을 누르면 beep가 종료되도록 수정 완료
