### ISSUE TITLE
System Testing#6 - Remove Alarm Mode

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#16]
알람을 기능에서 삭제했을 때 알람이 울림
-> 알람 모드가 선택되지 않았을 때는 알람이 울리지 않도록 수정

**Comment by 1hk-star** [comment]
[bug 수정 v1에 반영]
알람 기능을 off하면 -> resetAlarm을 호출하여 기존 알람 데이터를 모두 삭제.
다시 On을해도 기존 데이터는 복구가 안되게 수정하였습니다.
