### ISSUE TITLE
Static Anaylsis#1 - Unused import

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#6]
**Resolution Method: Unused import 제거**

- [x] Controller/Watch.java - line 10
<img width="477" alt="Screen Shot 2020-06-17 at 6 15 35 PM" src="https://user-images.githubusercontent.com/24283401/84879727-8afbea80-b0c6-11ea-8e55-a02ced101f0d.png">

- [x] Mode/Alarm.java - line 3 
<img width="483" alt="Screen Shot 2020-06-17 at 6 19 23 PM" src="https://user-images.githubusercontent.com/24283401/84880106-14132180-b0c7-11ea-8c15-5573563cf71f.png">

- [x] Mode/Buzzer.java - line 10
<img width="459" alt="Screen Shot 2020-06-17 at 6 19 56 PM" src="https://user-images.githubusercontent.com/24283401/84880162-268d5b00-b0c7-11ea-828f-1e6204fecf54.png">

- [x] Mode/FunctionActivator.java - line 3
<img width="464" alt="Screen Shot 2020-06-17 at 6 20 28 PM" src="https://user-images.githubusercontent.com/24283401/84880227-39a02b00-b0c7-11ea-9667-6027d1c06e02.png">

- [x]  Mode/FunctionActivator.java - line 9
![image](https://user-images.githubusercontent.com/24283401/84880585-a9161a80-b0c7-11ea-9da4-4e9908231480.png)

- [x] Mode/TimeKeep.java - line 12
<img width="377" alt="Screen Shot 2020-06-17 at 6 21 19 PM" src="https://user-images.githubusercontent.com/24283401/84880328-58062680-b0c7-11ea-9ded-bef3fc58b357.png">

- [x] Mode/TimeKeep.java - line 13
<img width="389" alt="Screen Shot 2020-06-17 at 6 21 32 PM" src="https://user-images.githubusercontent.com/24283401/84880359-5fc5cb00-b0c7-11ea-8ddf-a47dff719d7b.png">

- [x]  Mode/Worldtime.java - line 4
<img width="351" alt="Screen Shot 2020-06-17 at 6 21 44 PM" src="https://user-images.githubusercontent.com/24283401/84880394-67856f80-b0c7-11ea-90fd-89955405bbb1.png">

**Comment by dasd412** [comment]
안쓰는 imports문 삭제완료하였습니다.
