### ISSUE TITLE
Static Analysis#2 - Cyclomatic Complexity is N

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#7]
**Resolution Method: if- else if - else 문 줄이기 (ex switch문 사용)** 

- [x] Controller/Watch.java - line 191 ~ pressButton()
<img width="358" alt="Screen Shot 2020-06-17 at 6 27 21 PM" src="https://user-images.githubusercontent.com/24283401/84880957-30638e00-b0c8-11ea-981d-ac1c5b3b70d0.png">

- [x] Controller/Watch.java - line 312 ~ display()
<img width="352" alt="Screen Shot 2020-06-17 at 6 29 12 PM" src="https://user-images.githubusercontent.com/24283401/84881170-728ccf80-b0c8-11ea-9ed0-4b3db449c75a.png">

- [x] Mode/Dday.java - line 189 ~ plusDay()
<img width="330" alt="Screen Shot 2020-06-17 at 6 30 32 PM" src="https://user-images.githubusercontent.com/24283401/84881302-a1a34100-b0c8-11ea-85ff-41dd4b19fab9.png">

- [x] Mode/TimeKeep.java - line 179 ~ plusTime_time()
<img width="338" alt="Screen Shot 2020-06-17 at 6 32 55 PM" src="https://user-images.githubusercontent.com/24283401/84881535-f777e900-b0c8-11ea-845c-9702b27098a3.png">

**Comment by dasd412** [comment]
1.switch 문에서 case는 변수가 아닌 상수만 사용가능하므로 ~~.ordinal()이 아닌 ordinal()의 리턴 값 자체를 case의 값으로 지정하였습니다. 변경하고 나서 미리 만들어놓았었던 junit 테스트를 활용하여 다시 검사하였습니다. 그 결과 모두 패스했습니다.

**Comment by dasd412** [comment]
2.1과 동일한 방식입니다. 테스트 역시 재 컴파일 후 프로그램 동작을 확인하였고, 미리 작성한 테스트 케이스들을 적용한 결과 모두 통과했습니다.

**Comment by dasd412** [comment]
3.이미 switch case 문으로 작성되어있으며, 그 내부 if~else문은 더 이상 복잡도를 줄일 수 없을 것 같아 수정하지 않았습니다. 왜냐하면 내부 if~else문 로직은 윤년 고려, 월(30일인가 31일인가) 등등 여러가지 세부 사항을 모두 고려해야 하기 때문입니다. 

이 것을 수정하려면 코드 스멜을 없애는 리팩토링을 하는 것이 아니라 아예 새로운 알고리즘 로직자체를 작성해야 된다고 봅니다. 하지만 마지막 사이클인 관계로 그럴 수는 없다고 판단하여 서두에 언급한 대로 그대로 두었습니다.

**Comment by dasd412** [comment]
4. 3과 동일한 이유로 그대로 두었습니다.
