### ISSUE TITLE
Static Analysis#3 - Expression can be simplified

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#8]
**Resolution Method: if 문에서 true, false 표현 제거**

- [x] Controller/Watch.java - line 506
<img width="395" alt="Screen Shot 2020-06-17 at 6 36 40 PM" src="https://user-images.githubusercontent.com/24283401/84881919-7d942f80-b0c9-11ea-8bbe-87334a739404.png">

- [x] Controller/Watch.java - line 513
<img width="491" alt="Screen Shot 2020-06-17 at 6 37 10 PM" src="https://user-images.githubusercontent.com/24283401/84881979-8edd3c00-b0c9-11ea-91ad-560349d58982.png">

- [x] Controller/Watch.java - line 522
<img width="388" alt="Screen Shot 2020-06-17 at 6 37 24 PM" src="https://user-images.githubusercontent.com/24283401/84882007-97357700-b0c9-11ea-81e3-22285e478c6f.png">

- [x] Mode/FunctionActivator.java - line 55
<img width="388" alt="Screen Shot 2020-06-17 at 6 38 18 PM" src="https://user-images.githubusercontent.com/24283401/84882109-b7fdcc80-b0c9-11ea-8a14-f66a74c2f167.png">

- [x] Mode/FunctionActivator.java - line 86
<img width="446" alt="Screen Shot 2020-06-17 at 6 38 30 PM" src="https://user-images.githubusercontent.com/24283401/84882122-bf24da80-b0c9-11ea-8e98-c4d7f9ad7f39.png">

- [x] Mode/FunctionActivator.java - line 100
<img width="481" alt="Screen Shot 2020-06-17 at 6 38 49 PM" src="https://user-images.githubusercontent.com/24283401/84882150-c9df6f80-b0c9-11ea-92c6-604b0f808b2a.png">

- [x] Mode/FunctionActivator.java - line 110
<img width="435" alt="Screen Shot 2020-06-17 at 6 39 07 PM" src="https://user-images.githubusercontent.com/24283401/84882181-d49a0480-b0c9-11ea-828e-ee3cb3256638.png">

- [x] Mode/StopWatch.java - line 38
<img width="283" alt="Screen Shot 2020-06-17 at 6 39 40 PM" src="https://user-images.githubusercontent.com/24283401/84882234-e8456b00-b0c9-11ea-9ab5-24434fc8dae1.png">

- [x] Mode/StopWatch.java - line 99
<img width="269" alt="Screen Shot 2020-06-17 at 6 40 06 PM" src="https://user-images.githubusercontent.com/24283401/84882281-f7c4b400-b0c9-11ea-8085-3868a216ec0e.png">

- [x] Mode/StopWatch.java - line 117
<img width="346" alt="Screen Shot 2020-06-17 at 6 40 16 PM" src="https://user-images.githubusercontent.com/24283401/84882307-feebc200-b0c9-11ea-82e6-dbaefa3508e7.png">

**Comment by dasd412** [comment]
1.2.3. true 인 경우 ==true 삭제, false 인 경우 ==false 삭제하고 대신 ! 추가.

**Comment by dasd412** [comment]
4,5,6,7. 위의 것과 동일. 테스트는 functionActivator에 대한 junit 테스트 활용.

**Comment by dasd412** [comment]
8,9,10. 위의 예들과 동일. 테스트에 stopwatch용 junit 테스트 이용하였습니다.

**Comment by dasd412** [comment]
해당 이슈에 대해 수정을 하긴했지만, 개인적으로 의문이 드는 것이 있습니다.
true,false를 제거하면 코드가 단순해질 수 있다곤 해도 , 오히려 남겨 두면 코드가 더 명확해지지 않나요?
