### ISSUE TITLE
Static Analysis#4 - Avoid if (x != y) A; else B;

### ISSUE THREAD

**Issue by minjyo** [minjyo/softwareV_V#9]
**Resolution Method - if (x==y) B; else A; 문으로 수정**

- [x] Mode/Alarm.java - line 86 ~ showAlarm()
<img width="270" alt="Screen Shot 2020-06-17 at 6 45 08 PM" src="https://user-images.githubusercontent.com/24283401/84882745-abc63f00-b0ca-11ea-965d-fcd602899abb.png">

- [x]  Mode/Alarm.java - line 103 ~ cmpAlarm()
<img width="362" alt="Screen Shot 2020-06-17 at 6 47 39 PM" src="https://user-images.githubusercontent.com/24283401/84883015-05c70480-b0cb-11ea-93ba-f5f2aba95d00.png">

- [x]  Mode/Alarm.java - line 213 ~ deleteAlarm()
<img width="322" alt="Screen Shot 2020-06-17 at 6 48 27 PM" src="https://user-images.githubusercontent.com/24283401/84883118-21caa600-b0cb-11ea-8064-ef6fb678ea76.png">

- [x]  Mode/Buzzer.java - line 54 ~ subTimeBuzzer()
<img width="294" alt="Screen Shot 2020-06-17 at 6 51 04 PM" src="https://user-images.githubusercontent.com/24283401/84883461-80901f80-b0cb-11ea-9c71-87c3ab50770f.png">

- [x]  Mode/Dday.java - line 113 ~ showDday()
<img width="294" alt="Screen Shot 2020-06-17 at 6 51 50 PM" src="https://user-images.githubusercontent.com/24283401/84883551-9bfb2a80-b0cb-11ea-8446-6d1c222c94c2.png">

- [x]  Mode/Dday.java - line 128 ~ deleteDday()
<img width="289" alt="Screen Shot 2020-06-17 at 6 52 02 PM" src="https://user-images.githubusercontent.com/24283401/84883569-a3223880-b0cb-11ea-8ab4-38f30db0dfa5.png">

**Comment by dasd412** [comment]
해당 이슈 수정 완료.

개인 브랜치에서 리팩토링 -> 재 컴파일-> 리팩토링한 것에 대해 junit 테스트 -> 모든 것에 이상없다고 출력되어 마스터 브랜치로 푸시 순으로 진행하였습니다.
